apiVersion: v2

name: cert-manager-istio-csr
type: application
description: istio-csr enables the use of cert-manager for issuing certificates in Istio service meshes

home: https://cert-manager.io/docs/usage/istio-csr
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
- cert-manager
- istio
annotations:
  artifacthub.io/alternativeName: istio-csr
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: security
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/cert-manager/trust-manager
maintainers:
- name: cert-manager-maintainers
  email: cert-manager-maintainers@googlegroups.com
  url: https://cert-manager.io
sources:
- https://github.com/cert-manager/istio-csr

appVersion: v0.0.0
version: v0.0.0
