app:
  certmanager:
    namespace: istio-system
    preserveCertificateRequests: false
    additionalAnnotations:
    - name: firefly.venafi.com/policy-name
      value: 'ambient-policy'
    issuer:
      group: firefly.venafi.com
      kind: Issuer
      name: firefly-istio
  tls:
    trustDomain: cluster.local
    certificateDNSNames:
    - istio-csr.istio-system.svc
    - cert-manager-istio-csr.istio-system.svc

    rootCAFile: /etc/tls/root-cert.pem

# Loads the Issuer's root of trust to be set as Istio mesh trust anchors
volumes:
- name: root-ca
  secret:
    secretName: root-cert

volumeMounts:
- name: root-ca
  mountPath: /etc/tls
